name: CI

on:
  workflow_call: # From .github/workflows/Release.yml
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:
    if: always()
    name: all-jobs
    runs-on: ubuntu-latest
    needs:
      - cargo-fmt
      - cargo-clippy
      - cargo-test
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  cargo-fmt:
    name: cargo fmt -- --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check

  cargo-clippy:
    name: cargo clippy -- --deny clippy::all --deny clippy::pedantic ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: scripts/cargo-clippy.sh

  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    name: cargo test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --locked
