name: CI

on:
  workflow_call: # From .github/workflows/Release.yml
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  all-jobs:
    if: always() # Otherwise this job is skipped if the matrix job fails
    name: all-jobs
    runs-on: ubuntu-latest
    needs:
      - cargo-fmt
      - cargo-doc
      - cargo-clippy
      - cargo-audit
      - cargo-deny
      - cargo-test
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'

  cargo-fmt:
    name: cargo fmt -- --check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check

  cargo-doc:
    name: RUSTDOCFLAGS='--deny warnings' cargo doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: RUSTDOCFLAGS='--deny warnings' cargo doc --locked --no-deps --document-private-items

  cargo-clippy:
    name: cargo clippy -- --deny clippy::all --deny clippy::pedantic ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: scripts/cargo-clippy.sh

  cargo-audit:
    name: cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/cargo-audit.sh

  cargo-deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1

  cargo-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    name: cargo test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --locked
