name: Release

on:
  workflow_dispatch: # This workflow can only be triggered manually.

env:
  CARGO_TERM_COLOR: always

jobs:
  # Make sure regular CI passes before we make a release.
  ci:
    uses: ./.github/workflows/CI.yml

  # Publish the release to crates.io after regular CI passes and then create a
  # tag for the published crate.
  publish-and-tag:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: crates.io
      url: https://crates.io/crates/git-branch-deleter
    outputs:
      TAG_NAME: ${{ steps.tag-name.outputs.TAG_NAME }}
    steps:
      - uses: actions/checkout@v3
      - run: cargo publish -p git-branch-deleter
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: calculate tag name
        id: tag-name
        run: |
          version=$(cargo read-manifest --manifest-path Cargo.toml | jq --raw-output .version)
          echo "TAG_NAME=v${version}" >> $GITHUB_OUTPUT
      - name: push tag
        run: |
          git tag ${{ steps.tag-name.outputs.TAG_NAME }}
          git push origin ${{ steps.tag-name.outputs.TAG_NAME }}

  # Create a GitHub release for the new tag. Run this as a separate job 
  release:
    needs: publish-and-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed by softprops/action-gh-release.
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b # Commit from 2022-12-09 that I have personally audited the code of. I found no shenanigans.
        with:
          tag_name: ${{ needs.publish-and-tag.outputs.TAG_NAME }}
          generate_release_notes: false # TODO
