name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    uses: ./.github/workflows/CI.yml

  release:
    needs: ci
    environment:
      name: crates.io
      url: https://crates.io/crates/git-branch-deleter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Figure out what tag to use
      - name: calculate version
        id: version
        run: |
          version=$(cargo read-manifest --manifest-path Cargo.toml | jq --raw-output .version)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
          echo "GIT_TAG=v${version}" >> $GITHUB_OUTPUT

      # Try to cargo publish git-branch-deleter. If this succeeds we will tag
      # the release. This is because we don't want to have a situation where a
      # version exists at crates.io but not as a git tag.
      - run: cargo publish -p git-branch-deleter
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # Push the tag to git.
      - name: push tag
        run: |
          git tag ${{ steps.version.outputs.GIT_TAG }}
          git push origin ${{ steps.version.outputs.GIT_TAG }}
